### DISCUSSION TITLE
Self hosting stuck on preparing/syncing

### DISCUSSION THREAD

**Discussion by rhyst** [anyproto/contributors#196] [Self-hosting]
Hello, I am running a self hosted instance of any sync. I have successfully connected to it using the Android and desktop apps and notes appear to sync between them.

However in both clients the status indicator always shows “preparing” or “syncing” and never “synced”. This is despite the fact that syncing does appear to work.

Is there anyway to debug this? My network topology is the default (1 of each container except sync node of which there are three) and none of the logs appear to show any errors.

Thanks!

**Comment by fb929** [comment]
hi!
It looks like you don't have a connection with self-hosted, files are syncing only between clients via P2P.
You need to check the availability of your self-hosted cluster from the clients and also ensure that its address is present in the configuration file client.yml (or heart.yml).
For this, you can use the utilities telnet. 
Additionally, you can use [netcheck](https://github.com/anyproto/any-sync-tools/blob/main/any-sync-netcheck/README.md), but at the moment it can only check the availability of coordinators.

**Comment by rhyst** [comment]
Thanks for the reply. 

I checked all the tcp ports with telnet and they connected to the containers correctly. I used `nc` to check that I could connect to the UDP ports on the server though the containers did not produce any output from anything I sent. I ran another `nc` instance on the server with the containers stopped to at least confirm that the udp ports were open which they were.

I did notice one error in the `nodes` as a result of starting/stopping them:
```
2024-05-29T17:48:46.262Z        INFO    common.net.peer serve connection error  {"error": "manager closed: EOF", "errorVerbose": "manager closed: EOF\n\tstorj.io/drpc/drpcmanager.(*Manager).manageReader:234"}
```

Is this relevant? They stop after a small amount of time so I think it is just due to the containers booting.

**Comment by rhyst** [comment]
BTW: I could not get [netcheck](https://github.com/anyproto/any-sync-tools/blob/main/any-sync-netcheck/README.md) to run. The downloaded binaries gave me an error:

```
❯ any-sync-netcheck -v
any-sync-netcheck: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by any-sync-netcheck)
any-sync-netcheck: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by any-sync-netcheck)
```
And installing with `go install` did not produce a binary as far as I could tell.

**Reply by fb929** [reply]
> BTW: I could not get [netcheck](https://github.com/anyproto/any-sync-tools/blob/main/any-sync-netcheck/README.md) to run. The downloaded binaries gave me an error:
> 
> ```
> ❯ any-sync-netcheck -v
> any-sync-netcheck: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by any-sync-netcheck)
> any-sync-netcheck: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by any-sync-netcheck)
> ```
> 
> And installing with `go install` did not produce a binary as far as I could tell.

The packages are built on Ubuntu 22.04, so it looks like your system is not compatible. Try installing from the source code.
ubuntu-22.04
go install github.com/anyproto/any-sync-tools/any-sync-netcheck@latest

**Reply by rhyst** [reply]
Cloning repo and running `make build` worked :)

**Comment by rhyst** [comment]
If I used my heart.yml file unmodified then I get the following:

```
GoOS: linux
Kernel: Linux
Core: 5.15.146.1-microsoft-standard-WSL2
Platform: x86_64
OS: GNU/Linux
Hostname: pc
CPUs: 16
2024-05-30T20:09:17.911+0100    INFO    common.net.secure       secure service init     {"peerId": "<my-peer-id>"}
2024-05-30T20:09:17.911+0100    WARN    netcheck        open TCP conn error     {"addr": "yamux://<my-ip>:4830", "error": "dial tcp: address yamux://<my-ip>:4830: too many colons in address", "dur": "4.847µs"}
2024/05/30 20:09:17 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024-05-30T20:09:18.419+0100    INFO    netcheck        success {"addr": "<my-ip>:5830", "ip": "quic://<my-ip>:5830", "dur": "507.123562ms"}
```

If I modify the `heart.yml` to remove `yamux://` then I get:

```
GoOS: linux
Kernel: Linux
Core: 5.15.146.1-microsoft-standard-WSL2
Platform: x86_64
OS: GNU/Linux
Hostname: pc
CPUs: 16
2024-05-30T20:11:59.939+0100    INFO    common.net.secure       secure service init     {"peerId": "<my-peer-id>"}
2024-05-30T20:12:00.207+0100    INFO    netcheck        success {"addr": "<my-ip>:4830", "ip": "<my-ip>:4830", "dur": "267.738282ms"}
2024/05/30 20:12:00 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024-05-30T20:12:00.429+0100    INFO    netcheck        success {"addr": "<my-ip>:5830", "ip": "quic://<my-ip>:5830", "dur": "221.861385ms"}
```

However with the modfied file syncing still does not happen.

**Comment by fb929** [comment]
Please show your `etc/client.yml` file.

**Reply by rhyst** [reply]
```
networkId: N5AH7JCDmLN7vQCbkAQwWgamKNULKBg4dtXum67yVVNWWbKV
nodes:
  - peerId: 12D3KooWPvYs9oopYTkSFdfdBsJDcRZQYtXyj3dN1sYzyGYfEgVV
    addresses:
      - yamux://<my-ip>:4830
      - quic://<my-ip>:5830
    types:
      - coordinator
  - peerId: 12D3KooWLS9fNC4SqhaREmDKwTg4FFExfwQiWofgJjq3aLb12f47
    addresses:
      - yamux://<my-ip>:4530
      - quic://<my-ip>:5530
    types:
      - consensus
  - peerId: 12D3KooWMSAYxpwz1Kiu2DsBwWp3pbywwBK65zpcB9RdLKEi4yT6
    addresses:
      - yamux://<my-ip>:4430
      - quic://<my-ip>:5430
    types:
      - tree
  - addresses:
      - yamux://<my-ip>:4431
      - quic://<my-ip>:5431
    peerId: 12D3KooWPGLGcbxnUviSr4gxjBeRgjaDcQVjiBzSMxTX8iUwUATZ
    types:
      - tree
  - addresses:
      - yamux://<my-ip>:4432
      - quic://<my-ip>:5432
    peerId: 12D3KooWQSBuQvJmq8co4GxmHkrD9Q1uhPyDu6t3VRBFSKXriGaz
    types:
      - tree
  - peerId: 12D3KooWKUjJSxgZzyU42yd4vyjiE1zkgvfhLD6PMbSr1wvreMyz
    addresses:
      - yamux://<my-ip>:4730
      - quic://<my-ip>:5730
    types:
      - file
```
