### DISCUSSION TITLE
Understanding how/when syncs occur and debugging issues

### DISCUSSION THREAD

**Discussion by kylerm42** [anyproto/contributors#229] [Self-hosting]
I know I've gone off the beaten path a bit with my setup, but I'm looking to dive a bit deeper into understanding how the data is synced, when syncs happen, and troubleshooting issues.

My goal is to have reliable sync between multiple devices that aren't always on the same network as the any-sync services. I'm running the docker compose stack on my server, and have set up Cloudflare and Nginx Proxy Manager to handle all the endpoints in `client.yml`. This is what it looks like:

```
id: 66d5fb11bb830f001ad0fd48
networkId: N4EPNy7rh85V1Bg7KebTSmkGwgp3iTMoahCLEM2WT2onGANh
nodes:
  - addresses:
      - any-sync-node-1:1001
      - quic://any-sync-node-1:1011
      - anysync-node-1.mydomain.com:443
      - quic://anysync-node-1-quic.mydomain.com:443
      - 127.0.0.1:1001
      - quic://127.0.0.1:1011
    peerId: 12D4KooWAs7pg72QDr7ZXxiMtzwtDB6HhPgg22QxQv235SunydxV
    types:
      - tree
  - addresses:
      - any-sync-node-2:1002
      - quic://any-sync-node-2:1012
      - anysync-node-2.mydomain.com:443
      - quic://anysync-node-2-quic.mydomain.com:443
      - 127.0.0.1:1002
      - quic://127.0.0.1:1012
    peerId: 12D4KooWGKZNsZK7QsUndMtBroHQAAUAgwrHERPdCUSxD6zNmA1P
    types:
      - tree
  - addresses:
      - any-sync-node-3:1003
      - quic://any-sync-node-3:1013
      - anysync-node-3.mydomain.com:443
      - quic://anysync-node-3-quic.mydomain.com:443
      - 127.0.0.1:1003
      - quic://127.0.0.1:1013
    peerId: 12D4KooWLoB6a8A6fbcXpgKnzpbRvM7uy2ppi4RfuiW6y1eeycyX
    types:
      - tree
  - addresses:
      - any-sync-coordinator:1004
      - quic://any-sync-coordinator:1014
      - anysync-coordinator.mydomain.com:443
      - quic://anysync-coordinator-quic.mydomain.com:443
      - 127.0.0.1:1004
      - quic://127.0.0.1:1014
    peerId: 12D4KooWMC7MfCM3Myg79kx6MAUtQUrihKnJNisGwTgkhizyTuxt
    types:
      - coordinator
  - addresses:
      - any-sync-filenode:1005
      - quic://any-sync-filenode:1015
      - anysync-files.mydomain.com:443
      - quic://anysync-files-quic.mydomain.com:443
      - 127.0.0.1:1005
      - quic://127.0.0.1:1015
    peerId: 12D4KooWH2jcFKsDhnin1P8e4z9sju8ptQa6jtCTRSoSWktpJARH
    types:
      - file
  - addresses:
      - any-sync-consensusnode:1006
      - quic://any-sync-consensusnode:1016
      - anysync-consensus.mydomain.com:443
      - quic://anysync-consensus-quic.mydomain.com:443
      - 127.0.0.1:1006
      - quic://127.0.0.1:1016
    peerId: 12D4KooWA7XXHprzevEqx53dgUajS9fVudw5mhGTWdeS5aGvaZVv
    types:
      - consensus
```

Quick question about that, do I need the local addresses (e.g. `any-sync-node-1:1001`, `quic://127.0.0.1:1011`, etc) in my client.yml if my client isn't on the same device?

Syncs _seem_ to work, but they take a while to show up sometimes, and the statuses in the client are confusing. For example, here's the sync status for the app on my Macbook:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/7ffa9d29-3327-49d1-aa17-278d0104d722">
It appears that the `client(3).yml` file is still in progress, but it is showing up on my phone and I'm able to download it. My phone, however, always either shows `Preparing...` or `No connection`, even though it will get updates.

For a basic understanding, is the gist that both devices have to be online for syncs to happen? So if I make a change on my phone, close the app, then go to my PC later, it won't recognize the changes because the phone app isn't connected? Are there any logs from the any-sync services that would help understand or see when these syncs are occurring. I haven't been able to parse anything useful from them yet.

Thanks for your help!
