### DISCUSSION TITLE
Has anyone succesfully deployed selfhosted anytype with Cloudflare tunnels?

### DISCUSSION THREAD

**Discussion by Buco7854** [anyproto/contributors#241] [Self-hosting]
Hello,
Has anyone succesfully deployed selfhosted anytype with Cloudflare tunnels? If yes how have you done? Cannot find an udp option in cloudflare tunnels and it seems like any-sync use UDP and QUIC.
Seems like there might be a way to use udp with cloudflare tunnel but its kind of confusing and isn't as straightforward as other protocols.

I do not want to open ports on my firewall. I use [anysync-dockercompose](https://github.com/anyproto/any-sync-dockercompose).

**Comment by kebbakanyi** [comment]
I couldn’t get this working with a Cloudflare tunnel, but using my server’s Tailscale IP did the trick. Not the perfect setup, but it works for now. 
Figured I’d share in case it helps anyone else. There doesn’t seem to be much talk about Cloudflare tunneling online.

**Comment by itssoap** [comment]
I am also working with Tailscale for now, but with CF tunnels, I would recommend creating tunnels for all essential ports, but cloudflared only allows forwarding a TCP port for now, not sure of UDP and QUIC ports.

**Reply by Buco7854** [reply]
Well for now I'm using WARP with strict policy instead but users are forced to have the cloudflare client on their machine.

**Reply by itssoap** [reply]
Ohh I checked further, I was wrong. Understandable configuration you have. I would then recommend the usage of this flag along with `cloudflared`
https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/cloudflared-parameters/run-parameters/#protocol

So, define tunnels for the `ANY_SYNC_.*_PORT` in the .env file, run local tunnels for QUIC, then set the network address to localhost. Hoping that this works

**Comment by dizzyi** [comment]
# Remark
I use this method successfully login to the anytype server through Cloudflare tunnel with my roaming mobile device.

I don't know if there's any security issue.

## **However**
#### Failed to login to the same vault with another device (linux laptop), encountered this error message
> https://github.com/anyproto/anytype-heart/issues/2447

#### Then I make a new vault, and try to invite my phone to my laptop using QR and Link.
> The phone loaded for a while, and have permission erorr message.

#### Then I try to invite my laptop to my phone instead
> When I press the share link button in the mobile app, it simply does not response, no link is generated. 
> > but when I use the official anytype network, the share space button work again. 

I don't know if the my workaround caused these issue, or if I have anything setup wrong in my docker setting, or is there the issue of the application.

# Method
in cloudflare tunnel setting:
|routes|service|
|---|---|
|`any-sync-node-1.my.domain`|`https://192.168.0.300:1001`|
|`any-sync-node-2.my.domain`|`https://192.168.0.300:1002`|
|`any-sync-node-3.my.domain`|`https://192.168.0.300:1003`|
|`any-sync-coordinator.my.domain`|`https://192.168.0.300:1004`|
|`any-sync-filenode.my.domain`|`https://192.168.0.300:1005`|
|`any-sync-consensusnode.my.domain`|`https://192.168.0.300:1006`|

modified the `client.yml` file
```yaml
id: XXX
networkId: XXX
nodes:
  - addresses:
      - any-sync-node-1:1001
      - quic://any-sync-node-1:1011
      - 192.168.0.300:1001
      - quic://192.168.0.300:1011
      - 127.0.0.1:1001
      - quic://127.0.0.1:1011

      # ++++++++++++++++++++++++++++++++++++
      - any-sync-node-1.my.domain
      # ++++++++++++++++++++++++++++++++++++

    peerId: XXX
    types:
      - tree
  - addresses:
      - any-sync-node-2:1002
      - quic://any-sync-node-2:1012
      - 192.168.0.300:1002
      - quic://192.168.0.300:1012
      - 127.0.0.1:1002
      - quic://127.0.0.1:1012

      # ++++++++++++++++++++++++++++++++++++
      - any-sync-node-2.my.domain
      # ++++++++++++++++++++++++++++++++++++

    peerId: XXX
    types:
      - tree
  - addresses:
      - any-sync-node-3:1003
      - quic://any-sync-node-3:1013
      - 192.168.0.300:1003
      - quic://192.168.0.300:1013
      - 127.0.0.1:1003
      - quic://127.0.0.1:1013
      - any-sync-node-3.my.domain
    peerId: XXX
    types:
      - tree
  - addresses:
      - any-sync-coordinator:1004
      - quic://any-sync-coordinator:1014
      - 192.168.0.300:1004
      - quic://192.168.0.300:1014
      - 127.0.0.1:1004
      - quic://127.0.0.1:1014

      # ++++++++++++++++++++++++++++++++++++
      - any-sync-coordinator.my.domain
      # ++++++++++++++++++++++++++++++++++++
    
    peerId: XXX
    types:
      - coordinator
  - addresses:
      - any-sync-filenode:1005
      - quic://any-sync-filenode:1015
      - 192.168.0.300:1005
      - quic://192.168.0.300:1015
      - 127.0.0.1:1005
      - quic://127.0.0.1:1015

      # ++++++++++++++++++++++++++++++++++++
      - any-sync-filenode.my.domain
      # ++++++++++++++++++++++++++++++++++++

    peerId: XXX
    types:
      - file
  - addresses:
      - any-sync-consensusnode:1006
      - quic://any-sync-consensusnode:1016
      - 192.168.0.300:1006
      - quic://192.168.0.300:1016
      - 127.0.0.1:1006
      - quic://127.0.0.1:1016

      # ++++++++++++++++++++++++++++++++++++
      - any-sync-consensusnode.my.domain
      # ++++++++++++++++++++++++++++++++++++
      
    peerId: XXX
    types:
      - consensus
```
