### DISCUSSION TITLE
Maximum number of editors in a workspace

### DISCUSSION THREAD

**Discussion by StefanBiermann** [anyproto/contributors#278] [Self-hosting]
Hi there!

We switched to a self hosted system, because we share our spaces with a group of people that should be editors.
After setting up the self hosting docker compose system i had to recognize, that the limit for editors per (shared) space is still 3.
Following the description on the website, we can set this limit by ourself when self hosting.
Can anyone tell me where to set this limit to a higher number?

Thanks in advance!

**Comment by fb929** [comment]
If you are using [any-sync-dockercompose](https://github.com/anyproto/any-sync-dockercompose), you need to check the `./etc/any-sync-coordinator/config.yml` file.  

Make sure the limits are set:  
```yaml
defaultLimits:
  spaceMembersRead: 1000
  spaceMembersWrite: 1000
  sharedSpacesLimit: 1000
```
