### DISCUSSION TITLE
Self-hosted files not getting written to S3 bucket

### DISCUSSION THREAD

**Discussion by timatlee** [anyproto/contributors#290] [Self-hosting]
I'm using Garage as my s3 object store of choice, which for every other application has been a drop-in replacement for minio or s3.

I've updated the filenode configuration to reflect local setup:
```
s3Store:
  bucket: anytype
  indexBucket: anytype
  maxThreads: 2
  profile: default
  region: garage
  endpoint: http://s3.home.network.com
  forcePathStyle: true # 'true' for self-hosted S3 Object Storage
```

filenode contains `/root/.aws/credentials`, which contains the following content:
```
[default]
aws_access_key_id=GK1e...
aws_secret_access_key=...
```

I can connect to the bucket using the aws cli from another host, so I'm pretty confident that I have the right credentials.

Filenode isn't showing any errors at all - it's like it's quietly failing.  I was honestly hoping / expecting to see some sort of error that I could work from - but there's nothing.

I've tried with a few different syntaxes for the s3 bucket (s3://s3.., http://s3..:3900, etc..) without any obvious changes.

Help please? :)

thanks.
